language: node_js
node_js:
  - 12
cache:
  yarn: true
install:
  - yarn
script:
  - yarn build
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_token: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
